import './globals.css'
import { Roboto } from 'next/font/google'
import Header from './components/Header/page'
import Footer from './components/Footer/page'
const roboto = Roboto({ subsets: ['latin'], weight: [
  '400',
  '900'
] })

export const metadata = {
  title: 'Meu App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="pt-BR">
      <body className={`${roboto.className} bg-slate-950`} >
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  )
}
